export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_INVESTMENT = 'CREATE_INVESTMENT';
export const FETCH_INVESTMENTS = 'FETCH_INVESTMENTS';
export const FETCH_INVESTMENT = 'FETCH_INVESTMENT';
export const FETCH_INVESTMENTCONTRIBUTIONSUMMARY = 'FETCH_INVESTMENTCONTRIBUTIONSUMMARY';

export const INVEST = 'INVEST';
export const WITHDRAW_INVESTMENT = 'WITHDRAW_INVESTMENT';

export const MAKE_PAYMENT = 'MAKE_PAYMENT';
export const FETCH_ALLPAYMENTS = 'FETCH_ALLPAYMENTS';
export const WITHDRAW_PAYMENTS = 'WITHDRAW_PAYMENTS';

export const EXTRACT_INVESTMENTS = 'EXTRACT_INVESTMENTS';


export const FETCH_INVESTMENTMANAGER = 'FETCH_INVESTMENTMANAGER';
export const UPGRADE_INVESTMENTMANAGER_RANKING = 'UPGRADE_INVESTMENTMANAGER_RANKING';

export const FETCH_ETH_PROVIDER_SUCCESS = 'FETCH_ETH_PROVIDER_SUCCESS';
export const FETCH_ETH_PROVIDER_ERROR = 'FETCH_ETH_PROVIDER_ERROR';